language: python
python:
  - "3.5"
sudo: false
addons:
  apt:
#    sources:
#      - sourceline: 'deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'
#        key_url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
    packages:
      - postgresql-9.4

# command to install dependencies
install:
  - "pip install --upgrade -r requirements.txt"
  - pip install -e .[dev]

# command to run tests
script: python -m gengine.app.tests.runner

# deploy to pypi
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
