language: python
dist: trusty
python:
  - "3.5"
sudo: false
addons:
  postgresql: "9.4"
services:
  - postgresql
env:
  - TEST_POSTGRES=/usr/lib/postgresql/9.4/bin/postgres
  - TEST_INITDB=/usr/lib/postgresql/9.4/bin/initdb

# command to install dependencies
install:
  - "pip install --upgrade -r requirements.txt"
  - pip install -e .[dev]

# command to run tests
script: python -m gengine.app.tests.runner

# deploy to pypi
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
