language: python
dist: trusty
python:
  - "3.5"
sudo: required
env:
  - TEST_POSTGRES=/usr/lib/postgresql/9.5/bin/postgres TEST_INITDB=/usr/lib/postgresql/9.5/bin/initdb
apt:
  packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
    - postgis
# command to install dependencies
install:
  - "pip install --upgrade -r requirements.txt"
  - pip install -e .[dev]

# command to run tests
script: python -m gengine.app.tests.runner

# deploy to pypi
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
